"use client";

import { useParams, useRouter } from "next/navigation";
import Image from "next/image";
import { useState } from "react";

const allPosts = [
  { id: 1, title: "How to Book a Verified Companion in Delhi: A First-Timer's Guide", excerpt: "New to booking with us? Here's exactly how verification, messaging, and payment work — no surprises, no confusion.", image: "/Webpimages/bannermodel.webp", author: "Delhi Girl Team", date: "Aug 28, 2026", readTime: "5 min", tags: ["First-Timers", "Booking Guide"], content: [{ heading: "What 'Verified' Actually Means", body: "Every profile listed on Delhi Girl goes through an identity check before it ever goes live. That means the photos you see are current, and the person who arrives is the same one you saw when you booked — no last-minute substitutions, no surprises at the door." }, { heading: "How the Booking Process Works", body: "Everything happens over WhatsApp. You message us with your location and rough timing, we share a shortlist of available companions who fit, you pick one, and we confirm the arrival window. The whole exchange usually takes a few minutes." }, { heading: "What to Have Ready Before You Message", body: "Your hotel name or area, your preferred time, and any specific companion type you're after (if you have one) speeds things up considerably. You don't need to share anything more personal than that to get a booking confirmed." }, { heading: "What Happens When She Arrives", body: "Arrivals are handled quietly and professionally — no lingering in lobbies, no drawing attention. Most companions are experienced with hotel check-ins and know how to move through a property without anyone noticing anything unusual." }, { heading: "Pay After You Meet", body: "There's no advance payment or deposit required for a standard booking. You confirm on WhatsApp, your companion arrives, and payment happens only once you've actually met — cash or UPI, whichever is easier for you." }] },
  { id: 2, title: "Dinner Date or Hotel Visit? Choosing the Right Companion Experience", excerpt: "Not every booking is the same kind of evening. Here's how to think about what you actually want before you message us.", image: "/Webpimages/download (34).webp", author: "Delhi Girl Team", date: "Aug 26, 2026", readTime: "5 min", tags: ["Companionship", "Booking Guide"], content: [{ heading: "Two Very Different Kinds of Bookings", body: "A quiet hotel visit and a dinner date call for a different kind of companion, and being clear about which one you want up front makes the whole booking smoother — for you and for her." }, { heading: "When a Dinner Date Makes More Sense", body: "If you want conversation, a public setting, and someone who can hold her own at a nice restaurant or lounge, say so when you message. We'll match you with a companion chosen for social ease, not just availability." }, { heading: "When a Hotel Visit Is the Right Call", body: "For a straightforward, private evening with no public component, a standard hotel booking is simpler to arrange and usually confirms faster." }, { heading: "How to Communicate What You Want", body: "There's no need to overexplain — a short line like 'dinner first, then back to my hotel' or 'just a visit tonight' is enough for us to match you correctly the first time." }, { heading: "Booking Either One", body: "Both are booked the same way, over WhatsApp, with payment after you meet. The only difference is what you tell us at the start." }] },
  { id: 3, title: "Airport to Hotel: Booking Companionship Near IGI Airport", excerpt: "Landing late or flying out early? Here's how bookings near Mahipalpur and Aerocity work around your flight schedule.", image: "/Webpimages/paschimvihar.webp", author: "Delhi Girl Team", date: "Aug 24, 2026", readTime: "5 min", tags: ["Area Guide", "First-Timers"], content: [{ heading: "Why Mahipalpur & Aerocity Move Faster", body: "Both areas sit minutes from IGI Airport, and we keep a wider bench of companions based specifically in this corridor — which means faster confirmations and shorter arrival windows than almost anywhere else we cover." }, { heading: "Coordinating Around Flight Times", body: "Tell us your terminal and expected exit time rather than a fixed hour. We'll time the booking around your actual arrival, not a slot that falls apart the moment your flight is delayed." }, { heading: "What Hotels We Cover Near the Airport", body: "From the NH-8 business hotel stretch to the transit-focused properties right behind the terminals, our Mahipalpur and Aerocity companions are used to quiet, quick check-ins at all of them." }, { heading: "Red-Eye Landings and Early Departures", body: "Late-night arrivals and early-morning flights out are some of our most common bookings in this corridor — timing doesn't need to be conventional for us to make it work." }, { heading: "Booking Before You Land", body: "You can message us before you've even landed. Share your flight details and hotel, and we'll have a companion ready to confirm the moment you're through immigration." }] },
  { id: 4, title: "Sector by Sector: Navigating Bookings Across Delhi NCR", excerpt: "Delhi NCR isn't one booking zone. Here's why telling us your exact sector or area matters more than you'd think.", image: "/Webpimages/hotel3.webp", author: "Delhi Girl Team", date: "Aug 20, 2026", readTime: "6 min", tags: ["Area Guide"], content: [{ heading: "Why 'Delhi' Isn't One Booking Zone", body: "Delhi NCR spans hundreds of square kilometres, and a companion based near Connaught Place isn't much use to someone staying in Dwarka Sector 21. The more specific you are, the faster and more accurate your match." }, { heading: "Dwarka's Sector System Explained", body: "Dwarka alone has over twenty sectors. We ask for your sector number specifically because it's the single biggest factor in how quickly someone can reach you." }, { heading: "Noida & Gurgaon: Corporate vs Residential", body: "Noida's Sector 62 and Gurgaon's Cyber City see mostly after-work corporate bookings, while residential sectors in both cities call for a quieter, more low-profile approach — we match companions accordingly." }, { heading: "Finding Your Nearest Coverage Area", body: "We maintain dedicated coverage in Aerocity, Connaught Place, Dwarka, Mahipalpur, Lajpat Nagar, Noida, and Gurgaon, with wider NCR coverage available on request." }, { heading: "Tell Us Your Sector, Not Just Your City", body: "A landmark, a sector number, or a hotel name will always get you a faster, more accurate booking than just naming the city." }] },
  { id: 5, title: "Discretion 101: How We Protect Your Privacy", excerpt: "Discretion is the reason most clients choose us in the first place. Here's exactly how we handle it, step by step.", image: "/Webpimages/download (35).webp", author: "Delhi Girl Team", date: "Aug 18, 2026", readTime: "5 min", tags: ["Safety & Discretion"], content: [{ heading: "Why Discretion Matters More Than People Admit", body: "Whether you're a first-timer or a regular, privacy is rarely a small concern — it's usually the deciding factor in whether someone books at all. We treat it that way." }, { heading: "How Bookings Are Handled on WhatsApp", body: "Every conversation happens on WhatsApp, never over a public form or email thread. Messages stay between you and our coordinators, and nothing is shared beyond what's needed to confirm the booking." }, { heading: "What We Never Ask For", body: "We don't need your full name, ID copies, or any payment details in advance. A location and a preferred time is genuinely all it takes." }, { heading: "How Companions Handle Hotel Check-Ins", body: "Our companions are experienced with quiet, professional arrivals at hotels and residences alike — no loitering in lobbies, no drawing attention from staff or other guests." }, { heading: "What Happens to Your Information After", body: "Once a booking is complete, there's no ongoing record tying you to it beyond what's needed for basic coordination. Your privacy doesn't end when the evening does." }] },
  { id: 6, title: "Independent, High Profile, or Model: Which Companion Fits Your Evening?", excerpt: "The different companion categories aren't just about price — here's what actually separates them.", image: "/Webpimages/download (36).webp", author: "Delhi Girl Team", date: "Aug 15, 2026", readTime: "5 min", tags: ["Companionship"], content: [{ heading: "The Difference Isn't Just Price", body: "Independent, high profile, and model companions each bring a different kind of evening, and understanding the difference helps you book the right one the first time." }, { heading: "Independent Companions Explained", body: "These are companions who set their own schedule and preferences, often bringing a more personal, easygoing energy to a booking — well suited to a relaxed, low-key evening." }, { heading: "High Profile & Model Profiles", body: "For a more polished evening — dinner, an event, or simply a companion who fits a five-star setting — our high profile and model profiles are chosen specifically for presentation and social ease." }, { heading: "Matching Personality, Not Just Photos", body: "We ask what kind of evening you're after — quiet, talkative, playful, reserved — and match on that as much as on category." }, { heading: "How to Ask for What You Actually Want", body: "Be specific when you message: the occasion, the setting, and the vibe you're after. It's the fastest way to get matched with the right companion instead of just the next available one." }] },
  { id: 7, title: "Corporate Travel Companions: What Business Travelers Should Know", excerpt: "Business trips to Delhi come with their own booking rhythm — here's what corporate clients ask us most.", image: "/Webpimages/JwMarriott_CP.webp", author: "Delhi Girl Team", date: "Aug 10, 2026", readTime: "5 min", tags: ["Companionship", "Booking Guide"], content: [{ heading: "Why Business Travellers Book Differently", body: "Corporate clients tend to book around meetings, not evenings — a free two hours between calls, a dinner after a conference, or a full evening once the workday finally ends." }, { heading: "Fluent English and Social Ease Matter", body: "For dinners, product launches, or after-work drinks with colleagues, we match you with companions chosen specifically for conversation and comfort in a professional setting, not just a hotel visit." }, { heading: "Hotel Etiquette for Corporate Bookings", body: "Business hotels see constant guest traffic, so a companion arriving to meet you draws no more attention than any other visitor — check-in stays quiet and professional." }, { heading: "Handling Multi-Day and Outstation Trips", body: "If your trip runs several days or takes you outside Delhi, let us know upfront — we can arrange a companion comfortable with a longer or travelling booking." }, { heading: "Booking Around a Packed Schedule", body: "Send your free windows as they open up rather than trying to plan the whole trip in advance — we'll work around whatever time you actually have." }] },
  { id: 8, title: "What to Expect on Your First Booking: Etiquette & Safety Tips", excerpt: "Booking for the first time can feel unfamiliar. Here's a plain, practical walkthrough of what actually happens.", image: "/Webpimages/tajmahalhotel_lajpatnagar.webp", author: "Delhi Girl Team", date: "Aug 05, 2026", readTime: "5 min", tags: ["First-Timers", "Safety & Discretion"], content: [{ heading: "Before You Message", body: "You don't need to prepare much — just know roughly where you'll be and when. Everything else gets sorted over WhatsApp." }, { heading: "What Information You'll Actually Need to Share", body: "Your location, preferred time, and any specific preference is enough. We don't ask for ID, full names, or payment details upfront." }, { heading: "What Happens When She Arrives", body: "Your companion arrives at the agreed time, checks in with you directly, and the evening proceeds at whatever pace you're both comfortable with." }, { heading: "Simple Etiquette That Goes a Long Way", body: "Basic courtesy — punctuality, respect, clear communication about what you want — makes for a better evening on both sides." }, { heading: "Pay After You Meet, Every Time", body: "No advance payment is ever required. You pay once your companion has arrived and you've confirmed everything's as expected." }] },
];

export default function BlogPost() {
  const params = useParams();
  const router = useRouter();
  const [liked, setLiked] = useState(false);
  const post = allPosts.find((p) => p.id === Number(params.id));

  if (!post) {
    return (
      <div style={{ minHeight: "100vh", display: "flex", alignItems: "center", justifyContent: "center", background: "#fdf9f5" }}>
        <div style={{ textAlign: "center" }}>
          <h2 style={{ fontSize: "24px", fontWeight: "bold", color: "#1f2937", marginBottom: "16px" }}>Blog post not found</h2>
          <button onClick={() => router.push("/blogs")} style={{ padding: "12px 24px", borderRadius: "9999px", background: "linear-gradient(to right, #7c3aed, #db2777)", color: "white", fontWeight: "600", border: "none", cursor: "pointer" }}>Back to Blogs</button>
        </div>
      </div>
    );
  }

  return (
    <div style={{ minHeight: "100vh", background: "linear-gradient(to bottom, #fdf9f5, #ffffff)", paddingTop: "80px" }}>
      <div style={{ position: "relative", height: "55vh", width: "100%", overflow: "hidden" }}>
        <Image src={post.image} alt={post.title} fill priority style={{ objectFit: "cover" }} />
        <div style={{ position: "absolute", inset: 0, background: "linear-gradient(to top, rgba(0,0,0,0.75), rgba(0,0,0,0.2), transparent)" }} />
        <button onClick={() => router.push("/blogs")} style={{ position: "absolute", top: "88px", left: "24px", display: "inline-flex", alignItems: "center", gap: "8px", background: "rgba(255,255,255,0.2)", backdropFilter: "blur(10px)", color: "white", padding: "10px 18px", borderRadius: "9999px", border: "1px solid rgba(255,255,255,0.3)", cursor: "pointer", fontWeight: "500", fontSize: "14px" }}>Back to Blogs</button>
        <div style={{ position: "absolute", bottom: 0, left: 0, right: 0, padding: "32px 24px", maxWidth: "800px", margin: "0 auto" }}>
          <div style={{ display: "flex", gap: "8px", flexWrap: "wrap", marginBottom: "16px" }}>
            {post.tags.map((tag) => (<span key={tag} style={{ padding: "4px 12px", borderRadius: "9999px", fontSize: "12px", fontWeight: "600", background: "rgba(255,255,255,0.2)", color: "white", border: "1px solid rgba(255,255,255,0.3)" }}>{tag}</span>))}
          </div>
          <h1 style={{ fontSize: "clamp(22px, 4vw, 40px)", fontWeight: "800", color: "white", lineHeight: "1.2", marginBottom: "12px" }}>{post.title}</h1>
          <div style={{ display: "flex", gap: "20px", color: "rgba(255,255,255,0.8)", fontSize: "14px" }}>
            <span>{post.author}</span>
            <span>{post.date} - {post.readTime} read</span>
          </div>
        </div>
      </div>
      <div style={{ maxWidth: "760px", margin: "0 auto", padding: "48px 24px" }}>
        <p style={{ fontSize: "18px", color: "#4b5563", lineHeight: "1.8", marginBottom: "40px", borderLeft: "4px solid #a855f7", paddingLeft: "20px", fontStyle: "italic" }}>{post.excerpt}</p>
        <div style={{ display: "flex", flexDirection: "column", gap: "36px" }}>
          {post.content.map((section, idx) => (
            <div key={idx}>
              <h2 style={{ fontSize: "20px", fontWeight: "700", color: "#1f2937", marginBottom: "12px", display: "flex", alignItems: "center", gap: "12px" }}>
                <span style={{ width: "32px", height: "32px", borderRadius: "50%", background: "linear-gradient(135deg, #7c3aed, #db2777)", display: "inline-flex", alignItems: "center", justifyContent: "center", color: "white", fontSize: "13px", fontWeight: "700", flexShrink: 0 }}>{idx + 1}</span>
                {section.heading}
              </h2>
              <p style={{ fontSize: "16px", color: "#6b7280", lineHeight: "1.8" }}>{section.body}</p>
            </div>
          ))}
        </div>
        <div style={{ marginTop: "48px", paddingTop: "32px", borderTop: "1px solid #f3f4f6", display: "flex", flexWrap: "wrap", gap: "10px" }}>
          {post.tags.map((tag) => (<span key={tag} style={{ padding: "6px 16px", borderRadius: "9999px", fontSize: "14px", background: "#f3e8ff", color: "#7c3aed", fontWeight: "500" }}>{tag}</span>))}
        </div>
        <div style={{ marginTop: "24px", display: "flex", gap: "12px" }}>
          <button onClick={() => setLiked(!liked)} style={{ padding: "10px 20px", borderRadius: "9999px", border: liked ? "1px solid #f9a8d4" : "1px solid #e5e7eb", background: liked ? "#fdf2f8" : "white", color: liked ? "#db2777" : "#6b7280", cursor: "pointer", fontWeight: "500", fontSize: "14px" }}>
            {liked ? "Liked!" : "Like"}
          </button>
        </div>
        <div style={{ marginTop: "56px", background: "white", borderRadius: "24px", padding: "32px", border: "1px solid #e9d5ff", textAlign: "center", boxShadow: "0 4px 24px rgba(124,58,237,0.08)" }}>
          <div style={{ fontSize: "36px", marginBottom: "12px" }}>🌸</div>
          <h3 style={{ fontSize: "22px", fontWeight: "700", color: "#1f2937", marginBottom: "8px" }}>Ready to Book?</h3>
          <p style={{ color: "#6b7280", marginBottom: "24px" }}>Message us on WhatsApp — verified companions, discreet booking, pay after you meet.</p>
          <a href="https://api.whatsapp.com/send?phone=918826482370" target="_blank" rel="noopener noreferrer" style={{ display: "inline-flex", alignItems: "center", gap: "8px", background: "linear-gradient(to right, #7c3aed, #db2777)", color: "white", padding: "14px 32px", borderRadius: "9999px", fontWeight: "600", textDecoration: "none", fontSize: "15px" }}>Book via WhatsApp</a>
        </div>
        <div style={{ marginTop: "36px", textAlign: "center" }}>
          <button onClick={() => router.push("/blogs")} style={{ color: "#7c3aed", fontWeight: "500", background: "none", border: "none", cursor: "pointer", fontSize: "15px" }}>Back to all articles</button>
        </div>
      </div>
    </div>
  );
}
