"use client";

import { useParams, useRouter } from "next/navigation";
import Image from "next/image";
import { useState } from "react";

const allPosts = [
  { id: 1, title: "How to Choose the Perfect Spa Therapy for Deep Relaxation", excerpt: "Confused between Swedish, Thai, and Aromatherapy? A crisp guide to pick the right treatment.", image: "/Webpimages/smiling.webp", author: "Delhi Body Spa", date: "Aug 20, 2025", readTime: "6 min", tags: ["Therapies", "Relaxation"], content: [{ heading: "Swedish Massage - For Total Relaxation", body: "Swedish massage is the classic go-to for stress relief. Using long gliding strokes, kneading, and gentle tapping, this technique improves blood circulation and releases muscle tension. Perfect if you sit at a desk all day." }, { heading: "Thai Massage - For Flexibility", body: "Thai massage combines acupressure with assisted yoga-like stretches. The therapist uses hands, knees, and feet to guide you through postures. It dramatically improves flexibility." }, { heading: "Aromatherapy - For Mind", body: "Aromatherapy uses essential oils like lavender, eucalyptus, and peppermint. Each oil targets a specific concern - lavender for anxiety, eucalyptus for congestion, rosemary for clarity." }, { heading: "Deep Tissue - For Chronic Pain", body: "Deep tissue massage targets deeper muscle layers using slower, forceful strokes to break up knots and relieve tension. Expect some discomfort followed by significant relief." }, { heading: "Book Your Session", body: "At Delhi Body Spa, all treatments are done by certified therapists in a hygienic, luxury environment. Walk in or book via WhatsApp." }] },
  { id: 2, title: "Female to Male Massage: Etiquette, Benefits and What to Expect", excerpt: "First time? Learn how to prepare, communicate preferences, and enjoy a respectful, professional session.", image: "/Webpimages/fashion-portrait-beautiful-blonde-model.webp", author: "Team DBS", date: "Aug 16, 2025", readTime: "5 min", tags: ["Female To Male Massage", "Guide"], content: [{ heading: "What Is F2M Massage?", body: "Female to Male (F2M) massage is a professional service where a trained female therapist performs massage on a male client. Completely legitimate, widely offered across India. All sessions are conducted with full professionalism and hygiene." }, { heading: "Benefits", body: "Reduced cortisol levels, improved blood circulation, relief from muscle soreness, better sleep quality, and a boost in overall mood and energy." }, { heading: "How to Prepare", body: "Shower before your appointment and avoid heavy meals 1-2 hours prior. Arrive 10 minutes early and communicate areas you want focused on or avoided." }, { heading: "Etiquette", body: "Respect is the foundation. Keep the conversation professional. If something feels uncomfortable, simply speak up - our therapists adjust immediately." }, { heading: "Book a Session", body: "F2M massage packages start from 1499 rupees. Book via WhatsApp or walk in. First-time clients receive a complimentary aroma foot soak." }] },
  { id: 3, title: "Couple Massage in Delhi: Make It a Date to Remember", excerpt: "From room ambiance to synchronized techniques - here is how couples can elevate their spa day.", image: "/Webpimages/young-woman-lying-alone.webp", author: "Team DBS", date: "Aug 12, 2025", readTime: "7 min", tags: ["Couple Massage", "Experience"], content: [{ heading: "Why Couples Choose Spa Days", body: "In today s fast-paced city life, quality time as a couple gets sacrificed. A couple spa day is one of the most intimate date ideas. Shared wellness experiences increase relationship satisfaction." }, { heading: "What Is Included", body: "Private room with soft lighting and rose petals, synchronized massage by two therapists, choice of Swedish or aromatherapy, herbal foot soak, mocktail welcome, and a flower bath." }, { heading: "The Ambiance", body: "Himalayan salt lamps, curated playlists, sandalwood diffusers, and silk-finish massage tables. This is not just a massage room - it is a date venue." }, { heading: "Choosing Therapies Together", body: "Couples can choose different therapies. One might prefer deep tissue while the other wants aromatherapy. We accommodate both simultaneously." }, { heading: "Pricing", body: "Couple packages start at 2999 rupees for 60 minutes. Extended 90-minute sessions at 4499 rupees. Book via WhatsApp for instant confirmation." }] },
  { id: 4, title: "Body to Body Spa: Myths vs. Reality", excerpt: "We debunk the most common misconceptions and explain the genuine wellness benefits.", image: "/Webpimages/pretty-sensual-blonde-model-laying-bed-enjoy-her-morning-luxury-hotel-wearing-burgundy-silk-nightdress-robe-blind-hairs-beauty-face-boudoir-style.webp", author: "Delhi Body Spa", date: "Aug 05, 2025", readTime: "4 min", tags: ["Body To Body", "Wellness"], content: [{ heading: "What Is B2B Massage?", body: "Body to body (B2B) massage is a therapeutic technique where the therapist uses their forearms, elbows, and body weight to deliver deeper pressure. A legitimate wellness practice offered in reputable spas worldwide." }, { heading: "Myth: It Is Not a Real Therapy", body: "Reality: B2B massage has roots in Nuru traditions from Japan and has been practiced professionally for decades. It is a recognized wellness treatment with measurable physical benefits." }, { heading: "Real Benefits", body: "Deeper muscle relief, improved skin texture from essential oil application, full-body stress release, improved lymph flow and detoxification, and an immersive relaxation experience." }, { heading: "Hygiene Protocol", body: "Medical-grade massage oil used. Tables sanitized between clients. Fresh disposable sheets and towels provided. Therapists undergo regular health checks." }, { heading: "Book a Session", body: "B2B sessions start at 2499 rupees for 60 minutes at select locations. Advance booking recommended. Contact via WhatsApp." }] },
  { id: 5, title: "Pre and Post-Spa Skincare: Keep That Glow for Days", excerpt: "Small routine changes before and after your session make a big difference.", image: "/Webpimages/modelg.webp", author: "Skin Studio", date: "Jul 28, 2025", readTime: "6 min", tags: ["Skin & Body", "Glow"], content: [{ heading: "Why Pre-Spa Prep Matters", body: "Most people arrive without preparation, missing significantly better results. A few simple steps beforehand open your pores and prime skin to absorb treatments more effectively." }, { heading: "Pre-Spa Routine", body: "Exfoliate your body to remove dead skin cells. Drink at least 2 liters of water. Avoid heavy creams or perfume on the day of your visit. Eat a light meal 1-2 hours before." }, { heading: "What to Avoid", body: "Avoid waxing or shaving on the same day. Skip vigorous exercise 4 hours before. Avoid retinol 48 hours before a body treatment. Avoid alcohol - it dehydrates skin." }, { heading: "Post-Spa Routine", body: "Drink 2-3 liters of water to flush out toxins. Use lukewarm showers to preserve oils absorbed by your skin. Skip makeup or heavy products for at least 6 hours." }, { heading: "Maintaining the Glow", body: "Use a lightweight body oil daily after your shower. Dry brush your skin 2-3 times a week. Schedule a spa session every 3-4 weeks for optimal skin health." }] },
  { id: 6, title: "Meet Our Foreigner Therapists: Training, Techniques and Ethics", excerpt: "World-class practices, certifications, and the philosophy behind our global therapist team.", image: "/Webpimages/young-woman.webp", author: "Delhi Body Spa", date: "Jul 21, 2025", readTime: "5 min", tags: ["Foreigner Therapist", "Standards"], content: [{ heading: "Why We Hire International Therapists", body: "Delhi Body Spa was founded on the belief Delhi deserves world-class wellness. We recruit certified therapists from Thailand, Russia, Ukraine, and Southeast Asia - regions with centuries of wellness tradition." }, { heading: "Training and Certification", body: "Every therapist holds a recognized certification from their home country. Before joining, they complete 40 hours of additional training covering hygiene protocols and service excellence." }, { heading: "Techniques They Bring", body: "Thai therapists specialize in traditional Thai yoga massage. Russian therapists excel in deep tissue and stone therapy. Southeast Asian therapists bring Balinese massage, reflexology, and body scrub expertise." }, { heading: "Ethics and Professionalism", body: "All sessions follow explicit client consent protocols. Therapists receive regular ethics training. We maintain zero tolerance for any boundary violations from either side." }, { heading: "Book Your Session", body: "Ask to meet your therapist before your session - we encourage it. Book via WhatsApp or visit any of our Delhi locations." }] },
  { id: 7, title: "Full Body Massage Spa in Delhi: Benefits, Types & Costs", excerpt: "First time? Learn how to get ready, pick the right massage, and have a nice, relaxing time.", image: "/Webpimages/staff.webp", author: "Delhi Body Spa", date: "Aug 21, 2026", readTime: "5 min", tags: ["Spa Tips", "Wellness"], content: [{ heading: "What Is a Full Body Massage Spa in Delhi?", body: "A full body massage spa is a calm and clean place where trained people use their hands to rub your body to help you feel good and relaxed. It is totally real and you can find these places all over Delhi. Everything is done with care, cleanliness, and respect." }, { heading: "Benefits", body: "Less stress, better blood flow, less body pain, deeper sleep, less worry, stronger immunity, and you feel happier and full of energy." }, { heading: "How to Prepare", body: "Take a shower before you come and don't eat heavy food 1-2 hours before. Come 10 minutes early and tell the therapist which spots hurt or which spots to avoid. Drink water before and after." }, { heading: "Choosing the Right Massage", body: "Swedish if it's your first time, Deep Tissue if you have pain, Aromatherapy if you are stressed, Hot Stone if you want to feel warm and calm, Thai if you want to stretch, Russian if your muscles are tired, and Couples if you want to come with your partner." }, { heading: "Book a Session", body: "Full body massage starts from Rs.1,499. Book on WhatsApp or just walk in. First-time guests get a free foot soak that smells nice. We have good therapists, clean rooms, and a fancy feel." }] },
  { id: 8, title: "Massage Etiquette: What to Know Before Your First Spa Session", excerpt: "First time? Learn how to behave, what to do, and how to enjoy your first spa visit like a pro.", image: "/Webpimages/celebrityspastaff.webp", author: "Delhi Body Spa", date: "Aug 22, 2026", readTime: "5 min", tags: ["Spa Tips", "Guide"], content: [{ heading: "What Is Massage Etiquette?", body: "Massage etiquette means the right way to act and behave when you go to a spa. It is about being nice, respectful, and knowing what to do so you and the therapist both have a good time. It makes your first visit easy and fun." }, { heading: "Be on Time", body: "Come 10-15 minutes early to your appointment. This gives you time to fill out forms, use the washroom, and relax before your massage starts. If you are late, your massage time gets cut short." }, { heading: "Talk to Your Therapist", body: "Tell your therapist if you want soft or hard pressure. Point out any spots that hurt. If something feels weird or uncomfortable, just say it. They are there to help you and will fix it right away." }, { heading: "Keep It Clean", body: "Take a shower before you come to the spa. It helps you feel fresh and makes the massage nicer for both of you. Also, don't wear strong perfume or lotion before your session." }, { heading: "Be Respectful", body: "Always be polite and kind to your therapist. Keep the talk professional and nice. If you feel shy or uncomfortable, just speak up. The therapist will always respect your feelings and adjust." }] },
];

export default function BlogPost() {
  const params = useParams();
  const router = useRouter();
  const [liked, setLiked] = useState(false);
  const post = allPosts.find((p) => p.id === Number(params.id));

  if (!post) {
    return (
      <div style={{ minHeight: "100vh", display: "flex", alignItems: "center", justifyContent: "center", background: "#fdf9f5" }}>
        <div style={{ textAlign: "center" }}>
          <h2 style={{ fontSize: "24px", fontWeight: "bold", color: "#1f2937", marginBottom: "16px" }}>Blog post not found</h2>
          <button onClick={() => router.push("/blogs")} style={{ padding: "12px 24px", borderRadius: "9999px", background: "linear-gradient(to right, #7c3aed, #db2777)", color: "white", fontWeight: "600", border: "none", cursor: "pointer" }}>Back to Blogs</button>
        </div>
      </div>
    );
  }

  return (
    <div style={{ minHeight: "100vh", background: "linear-gradient(to bottom, #fdf9f5, #ffffff)", paddingTop: "80px" }}>
      <div style={{ position: "relative", height: "55vh", width: "100%", overflow: "hidden" }}>
        <Image src={post.image} alt={post.title} fill priority style={{ objectFit: "cover" }} />
        <div style={{ position: "absolute", inset: 0, background: "linear-gradient(to top, rgba(0,0,0,0.75), rgba(0,0,0,0.2), transparent)" }} />
        <button onClick={() => router.push("/blogs")} style={{ position: "absolute", top: "88px", left: "24px", display: "inline-flex", alignItems: "center", gap: "8px", background: "rgba(255,255,255,0.2)", backdropFilter: "blur(10px)", color: "white", padding: "10px 18px", borderRadius: "9999px", border: "1px solid rgba(255,255,255,0.3)", cursor: "pointer", fontWeight: "500", fontSize: "14px" }}>Back to Blogs</button>
        <div style={{ position: "absolute", bottom: 0, left: 0, right: 0, padding: "32px 24px", maxWidth: "800px", margin: "0 auto" }}>
          <div style={{ display: "flex", gap: "8px", flexWrap: "wrap", marginBottom: "16px" }}>
            {post.tags.map((tag) => (<span key={tag} style={{ padding: "4px 12px", borderRadius: "9999px", fontSize: "12px", fontWeight: "600", background: "rgba(255,255,255,0.2)", color: "white", border: "1px solid rgba(255,255,255,0.3)" }}>{tag}</span>))}
          </div>
          <h1 style={{ fontSize: "clamp(22px, 4vw, 40px)", fontWeight: "800", color: "white", lineHeight: "1.2", marginBottom: "12px" }}>{post.title}</h1>
          <div style={{ display: "flex", gap: "20px", color: "rgba(255,255,255,0.8)", fontSize: "14px" }}>
            <span>{post.author}</span>
            <span>{post.date} - {post.readTime} read</span>
          </div>
        </div>
      </div>
      <div style={{ maxWidth: "760px", margin: "0 auto", padding: "48px 24px" }}>
        <p style={{ fontSize: "18px", color: "#4b5563", lineHeight: "1.8", marginBottom: "40px", borderLeft: "4px solid #a855f7", paddingLeft: "20px", fontStyle: "italic" }}>{post.excerpt}</p>
        <div style={{ display: "flex", flexDirection: "column", gap: "36px" }}>
          {post.content.map((section, idx) => (
            <div key={idx}>
              <h2 style={{ fontSize: "20px", fontWeight: "700", color: "#1f2937", marginBottom: "12px", display: "flex", alignItems: "center", gap: "12px" }}>
                <span style={{ width: "32px", height: "32px", borderRadius: "50%", background: "linear-gradient(135deg, #7c3aed, #db2777)", display: "inline-flex", alignItems: "center", justifyContent: "center", color: "white", fontSize: "13px", fontWeight: "700", flexShrink: 0 }}>{idx + 1}</span>
                {section.heading}
              </h2>
              <p style={{ fontSize: "16px", color: "#6b7280", lineHeight: "1.8" }}>{section.body}</p>
            </div>
          ))}
        </div>
        <div style={{ marginTop: "48px", paddingTop: "32px", borderTop: "1px solid #f3f4f6", display: "flex", flexWrap: "wrap", gap: "10px" }}>
          {post.tags.map((tag) => (<span key={tag} style={{ padding: "6px 16px", borderRadius: "9999px", fontSize: "14px", background: "#f3e8ff", color: "#7c3aed", fontWeight: "500" }}>{tag}</span>))}
        </div>
        <div style={{ marginTop: "24px", display: "flex", gap: "12px" }}>
          <button onClick={() => setLiked(!liked)} style={{ padding: "10px 20px", borderRadius: "9999px", border: liked ? "1px solid #f9a8d4" : "1px solid #e5e7eb", background: liked ? "#fdf2f8" : "white", color: liked ? "#db2777" : "#6b7280", cursor: "pointer", fontWeight: "500", fontSize: "14px" }}>
            {liked ? "Liked!" : "Like"}
          </button>
        </div>
        <div style={{ marginTop: "56px", background: "white", borderRadius: "24px", padding: "32px", border: "1px solid #e9d5ff", textAlign: "center", boxShadow: "0 4px 24px rgba(124,58,237,0.08)" }}>
          <div style={{ fontSize: "36px", marginBottom: "12px" }}>🌸</div>
          <h3 style={{ fontSize: "22px", fontWeight: "700", color: "#1f2937", marginBottom: "8px" }}>Ready to Experience It?</h3>
          <p style={{ color: "#6b7280", marginBottom: "24px" }}>Book your session at Delhi Body Spa - luxury therapy, professional therapists.</p>
          <a href="https://api.whatsapp.com/send?phone=918826482370" target="_blank" rel="noopener noreferrer" style={{ display: "inline-flex", alignItems: "center", gap: "8px", background: "linear-gradient(to right, #7c3aed, #db2777)", color: "white", padding: "14px 32px", borderRadius: "9999px", fontWeight: "600", textDecoration: "none", fontSize: "15px" }}>Book via WhatsApp</a>
        </div>
        <div style={{ marginTop: "36px", textAlign: "center" }}>
          <button onClick={() => router.push("/blogs")} style={{ color: "#7c3aed", fontWeight: "500", background: "none", border: "none", cursor: "pointer", fontSize: "15px" }}>Back to all articles</button>
        </div>
      </div>
    </div>
  );
}
